- hosts: all
  become: true
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: installed
      tags: [never, alpha]


    - name: install httpd
      yum:
         name: httpd
         state: installed 
      tags: [never, beta]
