- hosts: all
  become: true
  tasks:
    - name: group add  
      group: 
        name: ibm
        state: present
    - name: add user bob
        user:
          name: bob
          state: present
