- hosts: localhost
  become: true
  gather_facts: false
  vars_files: files_list.yml
  tasks:
          - name: exclude file path from checksum line
            comment: grep -v
          - name: Check current checksum
            stat: 
              path: "{{item.name}}"
            with_items: "{{files}}"
            register: exam


          - name: exclude file path from checksum line
             
            #    - debug:
            #  var: exam
     
          - debug: 
              msg: "check sum correct"
            when: '"{{item.item.checksum}}" == "{{item.stat.checksum}}"'
            loop: "{{exam.results}}"

          - debug:
              msg: "checksum not match"
            when: '"{{item.item.checksum}}" != "{{item.stat.checksum}}"'
            loop: "{{exam.results}}"
