- hosts: server1
  become: true
  gather_facts: no
  vars_files: 
    - user_list.yml
  tasks:
    - name: create user
      vars:
        password: "{{lookup('password','./password-{{item.name}} length=6')}}"
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        comment: "{{item.first|capitalize}} {{item.last|capitalize}}"
        password: "{{password | password_hash('sha512')}}"
        update_password: on_create
        state: present

      with_items: "{{users}}"
