- hosts: localhost
  vars_files:
    - /home/admin/file_check/files_list.yml

  tasks:
          - name: Check current checksum
            stat: 
              path: "{{item.name}}"
            with_items: "{{files}}"
            register: exam

          - debug:
                  var: exam


          - debug: 
              msg: "check sum correct"
            when: '"{{item.item.checksum}}" == "{{item.stat.checksum}}"'
            loop: "{{exam.results}}"

          - debug: 
              msg: "checksum not match"                                    
            when: '"{{item.item.checksum}}" != "{{item.stat.checksum}}"'
            loop: "{{exam.results}}"      
