- hosts: all
  become: true
  vars_files: /home/admin/user_create/user_list.yml
  tasks:
    - name: Create User
      vars:
        - password: "{{ lookup('password', './{{item.name}}-password.txt length=6') }}"

      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        comment: "{{item.first| capitalize}} {{item.middle | capitalize}} {{item.last | capitalize}}"
        password: "{{password | password_hash ('sha512')}}"
        update_password: on_create
        state: present

      with_items: "{{users}}" 
