- hosts: all
  become: true
  tasks:
    - copy:
        content: "hello world"
        dest: /tmp/abc11.txt
      notify: restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
        enabled: yes
