- hosts: all
  become: true
  tasks:
    - copy:
        content: "hello world"
        dest: /tmp/abc10.txt
      notify: restart_httpd

  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
        
